name: flutter_map_mbtiles_provider
description: MBTilesProvider was originally implemented as part of flutter_map package
version: 0.1.0
repository: https://github.com/DonWasyl/flutter_map_mbtiles_provider

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  path_provider: ^2.0.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
